name: Create Implementation Issue

on:
  discussion:
    types: [answered]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.discussion.category.name, 'theoretical-development')
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueBody = `
            ## Implementation of Theoretical Position
            
            This issue implements the theoretical position developed in [discussion #${github.event.discussion.number}](${github.event.discussion.html_url}).

            #editing with a Comment
            ### Decided Position
            ${github.event.discussion.answer.body}
            
            ### Implementation Tasks
            - [ ] Task 1
            - [ ] Task 2
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Implement: ${github.event.discussion.title}`,
              body: issueBody,
              labels: ['status:decided', 'implementation']
            });
