# .github/workflows/security-validation.yml
name: Security Validation

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  validate-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Determine repository security level
        id: repo-security
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          
          if [[ "$REPO_NAME" == "ksbc-public" ]]; then
            echo "level=L0" >> $GITHUB_OUTPUT
          elif [[ "$REPO_NAME" == "ksbc-candidate" ]]; then
            echo "level=L1" >> $GITHUB_OUTPUT
          elif [[ "$REPO_NAME" == "ksbc-cadre" ]]; then
            echo "level=L2" >> $GITHUB_OUTPUT
          else
            echo "Unknown repository: $REPO_NAME"
            exit 1
          fi
      
      - name: Validate document security classifications
        run: |
          REPO_LEVEL="${{ steps.repo-security.outputs.level }}"
          
          # Check all markdown files
          find . -name "*.md" | while read file; do
            # Skip README and non-content files
            if [[ "$file" == "./README.md" ]]; then
              continue
            fi
            
            # Extract security classification
            FILE_SECURITY=$(grep -A 10 "^---" "$file" | grep "security_classification:" | sed 's/security_classification: *//g' | tr -d ' \r')
            
            if [ -z "$FILE_SECURITY" ]; then
              echo "Error: $file is missing security classification in frontmatter"
              exit 1
            fi
            
            # Validate security level against repository
            if [ "$REPO_LEVEL" = "L0" ] && [ "$FILE_SECURITY" != "L0" ]; then
              echo "Error: $file has security classification $FILE_SECURITY in public repository"
              exit 1
            fi
            
            if [ "$REPO_LEVEL" = "L1" ] && [ "$FILE_SECURITY" = "L2" ]; then
              echo "Error: $file has security classification L2 in candidate repository"
              exit 1
            fi
          done