name: Weekly Documentation Team Sync
on:
  schedule:
    - cron: '20 07 * * 1'  # Every Monday at 7:20 UTC
jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create team sync issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Documentation team sync for week of ${{ steps.date.outputs.date }}
          ASSIGNEES: member1,member2,member3
          LABELS: meeting,documentation
          PINNED: true
          CLOSE_PREVIOUS: true
          BODY: |
            ### Agenda
            - [ ] Review previous action items
            - [ ] Discuss open documentation proposals
            - [ ] Vote on items ready for decision
            - [ ] Convert approved decisions to implementations
            - [ ] Assign implementation tasks
            
            ### Action items
            *Add action items during the meeting*