# .github/workflows/setup-labels.yml
name: Setup Repository Labels

on:
  workflow_dispatch:  # Manual trigger

jobs:
  setup-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Import Labels
        uses: micnncim/action-label-syncer@v1
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          manifest: .github/labels.yml